/*
 * Auto-generated workload-aware NCCL tuner policy table.
 * Generated by generate_tuner_policy.py from experimental data.
 *
 * Platform: 8x A100 (NVLink, single-node)
 * Collective: AllReduce
 *
 * Size bands:
 *   0: < 1 KB
 *   1: 1 KB - 16 KB
 *   2: 16 KB - 256 KB
 *   3: 256 KB - 1 MB
 *   4: 1 MB - 8 MB
 *   5: >= 8 MB
 */

#ifndef TUNER_POLICY_TABLE_H
#define TUNER_POLICY_TABLE_H

#define POLICY_NUM_BANDS 6
#define POLICY_NUM_MODES 2  // 0=sequential, 1=overlap

typedef struct {
    int algo;      // NCCL algo index (-1 = let NCCL decide)
    int proto;     // NCCL proto index (-1 = let NCCL decide)
    int nChannels; // recommended channel count (0 = let NCCL decide)
} PolicyEntry;

// policy_table[overlap_mode][size_band]
static const PolicyEntry policy_table[POLICY_NUM_MODES][POLICY_NUM_BANDS] = {
    // Mode 0: sequential
    {
        { -1, -1,  0 },  /* band 0 -> AUTO+AUTO */
        { -1, -1,  0 },  /* band 1 -> AUTO+AUTO */
        {  0,  1,  0 },  /* band 2 (32KB, 64KB) -> TREE+LL128 */
        {  1,  2,  0 },  /* band 3 (256KB) -> RING+SIMPLE */
        {  1,  1, 24 },  /* band 4 (1MB, 2MB, 4MB) -> RING+LL128 */
        {  1,  2, 16 }  /* band 5 (16MB, 64MB, 256MB) -> RING+SIMPLE */
    },
    // Mode 1: overlap
    {
        { -1, -1,  0 },  /* band 0 -> AUTO+AUTO */
        { -1, -1,  0 },  /* band 1 -> AUTO+AUTO */
        { -1, -1,  0 },  /* band 2 (32KB, 64KB) -> AUTO+AUTO */
        { -1, -1,  0 },  /* band 3 (256KB) -> AUTO+AUTO */
        {  0,  1,  4 },  /* band 4 (1MB, 2MB, 4MB) -> TREE+LL128 */
        {  1,  2, 24 }  /* band 5 (16MB, 64MB, 256MB) -> RING+SIMPLE */
    }
};

#endif // TUNER_POLICY_TABLE_H
